// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: proto/metrics/v1/metrics.proto

package metalert

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetricsCollectorService_Get_FullMethodName  = "/proto.metrics.v1.MetricsCollectorService/Get"
	MetricsCollectorService_Post_FullMethodName = "/proto.metrics.v1.MetricsCollectorService/Post"
)

// MetricsCollectorServiceClient is the client API for MetricsCollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsCollectorServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
}

type metricsCollectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsCollectorServiceClient(cc grpc.ClientConnInterface) MetricsCollectorServiceClient {
	return &metricsCollectorServiceClient{cc}
}

func (c *metricsCollectorServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, MetricsCollectorService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsCollectorServiceClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, MetricsCollectorService_Post_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsCollectorServiceServer is the server API for MetricsCollectorService service.
// All implementations must embed UnimplementedMetricsCollectorServiceServer
// for forward compatibility
type MetricsCollectorServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Post(context.Context, *PostRequest) (*PostResponse, error)
	mustEmbedUnimplementedMetricsCollectorServiceServer()
}

// UnimplementedMetricsCollectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsCollectorServiceServer struct {
}

func (UnimplementedMetricsCollectorServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMetricsCollectorServiceServer) Post(context.Context, *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedMetricsCollectorServiceServer) mustEmbedUnimplementedMetricsCollectorServiceServer() {
}

// UnsafeMetricsCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsCollectorServiceServer will
// result in compilation errors.
type UnsafeMetricsCollectorServiceServer interface {
	mustEmbedUnimplementedMetricsCollectorServiceServer()
}

func RegisterMetricsCollectorServiceServer(s grpc.ServiceRegistrar, srv MetricsCollectorServiceServer) {
	s.RegisterService(&MetricsCollectorService_ServiceDesc, srv)
}

func _MetricsCollectorService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsCollectorServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsCollectorService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsCollectorServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsCollectorService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsCollectorServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsCollectorService_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsCollectorServiceServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsCollectorService_ServiceDesc is the grpc.ServiceDesc for MetricsCollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsCollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.metrics.v1.MetricsCollectorService",
	HandlerType: (*MetricsCollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MetricsCollectorService_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _MetricsCollectorService_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metrics/v1/metrics.proto",
}
